name: create-release

on:
  workflow_dispatch:
    inputs:
      version-string:
        type: string
        required: true

jobs:
  create-release:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/create-release.yml@1.1.1
    with:
      solution-file-path: 'Source/Starship-Expansion-Project.sln'
      version-string: ${{ inputs.version-string }}
      artifacts: GameData README* CHANGELOG* Extras
